[package]
name = "monadic"
version = "0.1.0"
authors = ["Gabriel Riba <griba2001@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="monadic"

[dependencies]

[dev-dependencies]
num = "*"

